### PR TITLE
Throw error when login credentials are incorrect

### LINKED ISSUE #2979: Login with incorrect credentials gives login successful notification
When logging in with incorrect credentials, it should not show that login was successful and instead, notify that the password is incorrect and could not login.

Peek 2023-06-19 17-08

### PR DESCRIPTION
**Pull request by JessicaJHee**
Fixes #2979

### CODE REVIEW

File: src/openshift/cluster.ts [hunk 1]
```diff
@@ -430,7 +430,7 @@ export class Cluster extends OpenShiftItem {
         try {
             const result = await Progress.execFunctionWithProgress(
                 `Login to the cluster: ${clusterURL}`,
-                () => Cluster.cli.executeTool(Command.odoLoginWithUsernamePassword(clusterURL, username, passwd)));
+                () => Cluster.cli.executeTool(Command.odoLoginWithUsernamePassword(clusterURL, username, passwd), undefined, true));
```
Comment (datho7561) [inline src/openshift/cluster.ts:433]: The error is thrown correctly, but the incorrect password is in the error popup. I think it would be nice to catch the exception, then rethrow with a modified error message that doesn't contain the password. This would be important in the case that someone is doing a screencast of using the extension and types in their password incorrectly, since in that case, it would expose what the user typed in for the password, which is probably close to the actual password.

**Review by datho7561 — APPROVED** [review]
Looks good. Thanks, Jessica!
