### PR TITLE
Prevent crash when loading workspace with deleted folder

### LINKED ISSUE #3356: Extension fails to activate after installation from marketplace
I have multiple folders added to workspace. Every time I try to install the extension I get the error below. The folder watch call fails on does not exists for a while, but extension activation tries to watch it anyway for unknown reason.

image

```
2023-09-27 08:56:02.163 [error] Error: ENOENT: no such file or directory, watch '/Users/eskimo/Sources/podman-desktop/extensions/redhat-authentication'
    at FSWatcher.<computed> (node:internal/fs/watchers:247:19)
    at Object.watch (node:fs:2364:34)
    at ServerlessFunctionModel.addWatchers (/Users/eskimo/.vscode/extensions/redhat.vscode-openshift-connector-1.9.0-darwin-arm64/out/src/serverlessFunction/functionModel.js:120:39)
    at new ServerlessFunctionModel (/Users/eskimo/.vscode/extensions/redhat.vscode-openshift-connector-1.9.0-darwin-arm64/out/src/serverlessFunction/functionModel.js:29:14)
    at new ServerlessFunctionView (/Users/eskimo/.vscode/extensions/redhat.vscode-openshift-connector-1.9.0-darwin-arm64/out/src/serverlessFunction/view.js:36:35)
    at Function.getInstance (/Users/eskimo/.vscode/extensions/redhat.vscode-openshift-connector-1.9.0-darwin-arm64/out/src/serverlessFunction/view.js:43:47)
    at Object.<anonymous> (/Users/eskimo/.vscode/extensions/redhat.vscode-openshift-connector-1.9.0-darwin-arm64/out/src/openshift/openshiftItem.js:95:62)
    at Module.u._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:1271)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1371:10)
    at Module.load (node:internal/modules/cjs/loader:1171:32)
    at Module._load (node:internal/modules/cjs/loader:1012:12)
    at Function.f._load (node:electron/js2c/asar_bundle:2:13377)
    at Function.c._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:135:5630)
    at Function.m._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:132:29116)
    at Function.D._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:99:19764)
    at Module.require (node:internal/modules/cjs/loader:1195:19)
    at Module.patchedRequire [as require] (/Users/eskimo/.vscode/extensions/github.copilot-1.115.439/node_modules/diagnostic-channel/dist/src/patchRequire.js:16:46)
    at g (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:647)
    at Object.<anonymous> (/Users/eskimo/.vscode/extensions/redhat.vscode-openshift-connector-1.9.0-darwin-arm64/out/src/openshift/cluster.js:36:25)
    at Module.u._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:1271)
```

Running on Apple M1 Max, macOS 13.5.2 (22G91).

### PR DESCRIPTION
**Pull request by datho7561**
Fixes #3356

Signed-off-by: David Thompson <davthomp@redhat.com>

### CODE REVIEW

**Comment by datho7561** [comment]
@dgolovin if you have time, could you please check if this fixes your issue?

File: src/serverlessFunction/functionModel.ts [hunk 1]
```diff
@@ -123,13 +123,18 @@ export class ServerlessFunctionModel implements Disposable {
...
+                try {
+                    fs.accessSync(workspaceFolder.uri.fsPath);
+                    this.watchers.push(
+                        fs.watch(workspaceFolder.uri.fsPath, (_event, filename) => {
+                            if (filename === 'func.yaml') {
+                                this.view.refresh();
+                            }
+                        }),
+                    );
+                } catch (e) {
```
Comment (dgolovin) [inline src/serverlessFunction/functionModel.ts:135]: This catch will also catch fs.watch errors in case watcher cannot be installed. This error is very common when running on linux. There should be warning for the user that automatic updates for view are not going to be triggered due to filesystem watcher install failure.

**Review by dgolovin — APPROVED** [review]
Works for me.
See my comment about empty catch bloc added (fixing is optional).

File: src/serverlessFunction/functionModel.ts (hunk 1 above)
Comment (vrubezhny) [reply src/serverlessFunction/functionModel.ts:135]: Agree with @dgolovin here. We probably should show a warning message here.

**Review by vrubezhny — APPROVED** [review]
Looks good to me.

See @dgolovin's comment on file watcher setup error handling

File: src/serverlessFunction/functionModel.ts (hunk 1 above)
Comment (datho7561) [reply src/serverlessFunction/functionModel.ts]: Okay. I moved installing the file watcher out of the try/catch, and added an error message if the workspace folder doesn't exist, with an explanation why we are trying to watch it.
